# Generated by Django 4.2.1 on 2023-05-09 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ['-createdAt'], 'verbose_name_plural': 'words'},
        ),
        migrations.AlterModelTable(
            name='word',
            table='Words',
        ),
    ]
